### ISSUE TITLE
Disable adding player

### ISSUE THREAD

**Issue by davidflury** [holruum/holruum#5]
After i added two players it is pretty useless to still enable adding more players if i can not play woth more players (WHY NOT SUPPORT MANY PLAYERS?).
Disable the button. Or the input field. Or even better remove the button and display just two textfields. Or even much even betterer enable infinite players.

**Comment by davidflury** [comment]
No

**Comment by sebibrunner** [comment]
changed it. Design can still be improved, but hey...
